### ISSUE TITLE
About Baseline GETNext

### ISSUE THREAD

**Issue by Pursue1221** [Shirley-YFY/SNPM#1]
Thank you for your opensource code.

I am wondering how did you get the result of your baseline GETNext（Yang et al. 2022: GETNext: trajectory flow map enhanced transformer for next POI recommendation)?  I try to run GETNext on your datasets, and I find it needs extreamly large memory.
Even on the NVIDIA A100, CUDA still out of memory.

And have you use the category information for GETNext?

Looking forward your reply.

**Comment by Shirley-Ying** [comment]
I'm sorry, but the last time I worked on this project was over a year ago, and my memory is very vague. Regarding your question, I vaguely remember that there was an N^2 space complexity adjacency matrix in the code for GETNext, where N should be the number of POI points. At that time, I spent some time rewriting it to use a sparse matrix storage format because the original dataset used in the paper was small and didn't pose any problems. However, if you use the dataset I used in my paper, you may encounter memory issues. So, if my memory serves me correctly, you will need to make appropriate modifications before using the GETNext code. Also, since the dataset I used doesn't have any classification information, and my model doesn't utilize POI point classification, I didn't provide classification information for GETNext to maintain fairness in the comparison. Good luck!

**Comment by Pursue1221** [comment]
thank you so much.
